settings.outformat = "pdf";
size(x=15cm,y=9cm);
defaultpen(fontsize(18pt));
int L=10;
pair A = (0, 0);
pair B = (1, 2);
pair C = (5, 3);
pair R0 = (4, 0);
path orbit=A..B..C{right};
real w=linewidth();
pair b2 = (1, 2.7);
pair n1 = (1, 2);
pair n2 = (0.5, 2.4);
pair t2 = (1.6, 2.6);
//dot(A, linewidth(L*w));
//dot(B, linewidth(L*w));
//dot(C, linewidth(L*w));
path vecN = B--n2;
path vecB = B--b2;
path vecR = R0--B;
path vecT = B--t2;
draw("$R(s)$", vecR, EndArrow);
draw("$b$", vecB, align=NW, EndArrow);
draw("$n$", vecN, align=SW, EndArrow);
draw("$t$", vecT, align=NW, EndArrow);
draw("$S$", orbit, align=SE, 1+black, EndArrow);
